### ISSUE TITLE
Code?

### ISSUE THREAD

**Issue by artiedins** [haleqiu/AirIMU#1]
Great paper! When do you think you can release the code? What license are you considering for it?

**Comment by haleqiu** [comment]
Thank you @artiedins , I think I will release parts of the code this week. Because we are thinking of doing more experiments. We are going to release them step by step.

**Comment by Shiaoming** [comment]
> Thank you @artiedins , I think I will release parts of the code this week. Because we are thinking of doing more experiments. We are going to release them step by step.

Hello, is there any plan to release code?

**Comment by Shiaoming** [comment]
> Thank you @artiedins , I think I will release parts of the code this week. Because we are thinking of doing more experiments. We are going to release them step by step.

Hi, is there any new plan to release code?

**Comment by haleqiu** [comment]
@Shiaoming @artiedins Seems like I missed this post. 
Most of the code and pre-trained model is released months ago. If there are any questions, we will actively respond here.
