### ISSUE TITLE
how can i get b_acc and b_gyro?

### ISSUE THREAD

**Issue by JiangWeiHn** [haleqiu/AirIMU#10]
I appreciate your work。I trained the model based on custom data。I got the acc_cov and gyro_cov and found that all this cov are positive,and irrelevant to the b_acc and b_gyro 。and when I use the correction_acc and correction_gyro to denoise imu data,it too large to crash the the navigation program . sometime it even larger than the raw imu data .my imu coordinate system is different from EuRoCdataset . I define it x-> forward,y->left,and z->up. That is same with my lidar's coordinate. Does this have an impact？

**Comment by haleqiu** [comment]
@JiangWeiHn If the correction is exceptionally large. I believe there are some mistakes of the coordinate system in your custom dataset.

**Comment by haleqiu** [comment]
One easy way of unit testing your coordinates is by manually compensating for gravity. Since gravity is dominant in your acceleration, you should get a reasonable (small) value after you compensate for gravity.

**Comment by haleqiu** [comment]
We do have an auto-calibration script. But I don't think I can organize that before the ICRA. Will keep you update.

**Comment by JiangWeiHn** [comment]
OK .thanks you reply.I will try change the imu coordinate to  align it with the EuRoCdataset

**Comment by haleqiu** [comment]
@JiangWeiHn It is not about aligning it with the EuRoC dataset. What I was trying to say is to make sure you get the correct coordinate. Make sure you have a correct alignment between your sensor and the ground truth.

**Comment by JiangWeiHn** [comment]
我找到原因了，是我输入的数据有问题，谢谢。
