### ISSUE TITLE
train.py error

### ISSUE THREAD

**Issue by minhlenhat21** [haleqiu/AirIMU#6]
I try to download the TUM VI dataset but i can't find the "mav0/mocap0/grad_velo.txt" in there (your code load TUM VI has read this file) so basically i can't train with this dataset. Could you help me with that

**Comment by haleqiu** [comment]
Since TUM don't have velocity, we calculate velocity based on first-order differentiation.
In `/utils/deferentiate_vel.py`

**Comment by minhlenhat21** [comment]
I noticed in TUMVI file config, the name dataset that you used in training is so small compare to total TUMVI dataset. Does it affect the result ?

**Comment by haleqiu** [comment]
If I remember correctly, only parts of the TUMVI dataset contain the ground truth within Vicon.
@minhlenhat21
